import { reportEvent } from "./appMetrica";

export const AnalyticsEvent = {
  ScreenView: "screen_view",
  OnboardingSlideViewed: "onboarding_slide_viewed",
  OnboardingNext: "onboarding_next",
  OnboardingSkipped: "onboarding_skipped",
  LanguageSelected: "language_selected",
  ZodiacSelected: "zodiac_selected",
  OnboardingCompleted: "onboarding_completed",
  DashboardTabChanged: "dashboard_tab_changed",
  DashboardBotOpened: "dashboard_bot_opened",
  DashboardRefreshed: "dashboard_refreshed",
  HoroscopeCardOpened: "horoscope_card_opened",
  NotificationsAccepted: "notifications_accepted",
  ProfileSaved: "profile_saved",
  AppLinkShared: "app_link_shared",
  ProfileTabChanged: "profile_tab_changed",
  ProfileSettingsOpened: "profile_settings_opened",
  ProfileBotOpened: "profile_bot_opened",
  ProfileRefreshed: "profile_refreshed",
  AiAgentTabChanged: "ai_agent_tab_changed",
  AiAgentFollowToggled: "ai_agent_follow_toggled",
  AiAgentChatStarted: "ai_agent_chat_started",
  AiAgentReportOpened: "ai_agent_report_opened",
  AiAgentReportSubmitted: "ai_agent_report_submitted",
  AiAgentShare: "ai_agent_share",
  AiAgentEditOpened: "ai_agent_edit_opened",
  AiAgentDeleteConfirmed: "ai_agent_delete_confirmed",
  AiAgentDeleteSuccess: "ai_agent_delete_success",
  AiAgentRefreshed: "ai_agent_refreshed",
  AiAgentCreateStepViewed: "ai_agent_create_step_viewed",
  AiAgentCreateStepAdvanced: "ai_agent_create_step_advanced",
  AiAgentCreateCanceled: "ai_agent_create_canceled",
  AiAgentCreateAvatarAdded: "ai_agent_create_avatar_added",
  AiAgentCreateAvatarRemoved: "ai_agent_create_avatar_removed",
  AiAgentCreateGalleryAdded: "ai_agent_create_gallery_added",
  AiAgentCreateGalleryRemoved: "ai_agent_create_gallery_removed",
  AiAgentCreateCategoryToggled: "ai_agent_create_category_toggled",
  AiAgentCreateUsefulnessAdded: "ai_agent_create_usefulness_added",
  AiAgentCreateUsefulnessRemoved: "ai_agent_create_usefulness_removed",
  AiAgentCreateSubmitted: "ai_agent_create_submitted",
  AiAgentCreateCompleted: "ai_agent_create_completed",
  AiAgentCreateProfileOpened: "ai_agent_create_profile_opened",
  AiAgentCreateAnotherStarted: "ai_agent_create_another_started",
  AiAgentCreateDone: "ai_agent_create_done",
  AiAgentEditStepChanged: "ai_agent_edit_step_changed",
  AiAgentEditAvatarAdded: "ai_agent_edit_avatar_added",
  AiAgentEditAvatarRemoved: "ai_agent_edit_avatar_removed",
  AiAgentEditGalleryAdded: "ai_agent_edit_gallery_added",
  AiAgentEditGalleryRemoved: "ai_agent_edit_gallery_removed",
  AiAgentEditCategoryToggled: "ai_agent_edit_category_toggled",
  AiAgentEditUsefulnessAdded: "ai_agent_edit_usefulness_added",
  AiAgentEditUsefulnessRemoved: "ai_agent_edit_usefulness_removed",
  AiAgentEditSubmitted: "ai_agent_edit_submitted",
  NatalChartGenerateStarted: "natal_chart_generate_started",
  NatalChartGenerateSuccess: "natal_chart_generate_success",
  NatalChartGenerateFailed: "natal_chart_generate_failed",
  NatalChartCopy: "natal_chart_copy",
  NatalReadingOpen: "natal_reading_open",
  NatalReadingLoadSuccess: "natal_reading_load_success",
  NatalReadingLoadFailed: "natal_reading_load_failed",
  NatalReadingRetry: "natal_reading_retry",
  ChatsScreenViewed: "chats_screen_viewed",
  ChatsTabChanged: "chats_tab_changed",
  ChatsSearchPerformed: "chats_search_performed",
  ChatsRefreshed: "chats_refreshed",
  ChatsLoadMore: "chats_load_more",
  ChatOpened: "chat_opened",
  ChatDeleted: "chat_deleted",
  ChatMessagesViewed: "chat_messages_viewed",
  ChatMessagesRefreshed: "chat_messages_refreshed",
  ChatMessagesLoadMore: "chat_messages_load_more",
  ChatMessageSent: "chat_message_sent",
  ChatMessageEdited: "chat_message_edited",
  ChatMessageDeleted: "chat_message_deleted",
  ChatMessageCopied: "chat_message_copied",
  ChatMessagePinned: "chat_message_pinned",
  ChatMessageUnpinned: "chat_message_unpinned",
  ChatMessageReported: "chat_message_reported",
  ChatMessageReplyStarted: "chat_message_reply_started",
  ChatHistoryCleared: "chat_history_cleared",
  ChatPinnedMessageOpened: "chat_pinned_message_opened",
  ChatTypingStarted: "chat_typing_started",
  ChatTypingStopped: "chat_typing_stopped",
} as const;

export type AnalyticsEventName = (typeof AnalyticsEvent)[keyof typeof AnalyticsEvent];

export const trackEvent = async (
  name: AnalyticsEventName,
  attributes?: Record<string, unknown>,
) => reportEvent(name, attributes);
